---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-quarkus-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-quarkus-consumer
  template:
    metadata:
      labels:
        app: kafka-quarkus-consumer
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-kafka-release.default.svc.cluster.local:9092
          name: kafka-quarkus-consumer
          image: quarkus/quarkus-keda-scaler-jvm
          imagePullPolicy: IfNotPresent
